#' Train an ensemble learner for semi-supervised text scoring
#'
#' This function takes in a corpus of text documents or a set of computed text features, along with a sample
#' of human-coded outcome values and trains an ensemble of machine learning models to predict the outcome as a
#' function of machine measures of text.
#'
#' @param x a \code{data.frame} or matrix of numeric text features.
#' @param y a vector of human-coded scores for the outcome of interest.
#' @param z optional indicator for treatment assignment. If specified, separate ensembles will
#' be trained for each treatment group;
#' @param n.tune an integer denoting the amount of granularity in the tuning parameter grid.
#' By default, this argument is the number of levels for each tuning parameters that should be generated by \link{train}.
#' @param cvf number of folds for cross validation
#' @param bounds a vector (y1, y2) specifying the lower and upper limits for prediction
#' @param ... additional arguments passed to \link{trainControl}.
#' @param return.all should all component models be returned? If `FALSE`, returns only the fitted ensemble(s).
#' @return a fitted model object
#' @export

train_ensemble <- function(x, y, z=NULL, n.tune=3, cvf=5,
                   bounds=NULL, ..., return.all=TRUE){

  tmp=list(x,y,n.tune)
  return(tmp)

}
